feat: hack

diff --git a/.github/workflows/publish-release.yml b/.github/workflows/publish-release.yml
--- a/.github/workflows/publish-release.yml
+++ b/.github/workflows/publish-release.yml
@@ -57,54 +57,54 @@ jobs:
           fetch-tags: true
           # token: ${{ secrets.TEMP_SEMANTIC_RELEASE_GH_TOKEN }}
       
-      - name: Debug steps
-        run: |
-          echo ${{ github.ref_name }}
-          echo $GITHUB_ACTIONS
-          echo $GITHUB_EVENT_NAME
+      # - name: Debug steps
+      #   run: |
+      #     echo ${{ github.ref_name }}
+      #     echo $GITHUB_ACTIONS
+      #     echo $GITHUB_EVENT_NAME
       
-      # By default, `actions/checkout` after fetching leaves the repository in 
-      # a detached HEAD state. A semantic release refers to the name of the 
-      # current local branch; when the HEAD is detached, this name is empty.
-      - name: Switch to real named branch
-        if: ${{ github.event_name == 'pull_request' }}
-        run: git checkout -B "${{ github.head_ref }}"
+      # # By default, `actions/checkout` after fetching leaves the repository in 
+      # # a detached HEAD state. A semantic release refers to the name of the 
+      # # current local branch; when the HEAD is detached, this name is empty.
+      # - name: Switch to real named branch
+      #   if: ${{ github.event_name == 'pull_request' }}
+      #   run: git checkout -B "${{ github.head_ref }}"
 
-      - name: Force release branch to be at workflow sha
-        run: |
-          git reset --hard ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
+      # - name: Force release branch to be at workflow sha
+      #   run: |
+      #     git reset --hard ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
 
-      - name: Verify upstream has NOT changed
-        shell: bash
-        run: |
-          set +o pipefail
+      # - name: Verify upstream has NOT changed
+      #   shell: bash
+      #   run: |
+      #     set +o pipefail
 
-          UPSTREAM_BRANCH_NAME="$(git status -sb | head -n 1 | awk -F '\\.\\.\\.' '{print $2}' | cut -d ' ' -f1)"
-          printf '%s\n' "Upstream branch name: $UPSTREAM_BRANCH_NAME"
+      #     UPSTREAM_BRANCH_NAME="$(git status -sb | head -n 1 | awk -F '\\.\\.\\.' '{print $2}' | cut -d ' ' -f1)"
+      #     printf '%s\n' "Upstream branch name: $UPSTREAM_BRANCH_NAME"
 
-          set -o pipefail
+      #     set -o pipefail
 
-          if [ -z "$UPSTREAM_BRANCH_NAME" ]; then
-              printf >&2 '%s\n' "::error::Unable to determine upstream branch name!"
-              exit 1
-          fi
+      #     if [ -z "$UPSTREAM_BRANCH_NAME" ]; then
+      #         printf >&2 '%s\n' "::error::Unable to determine upstream branch name!"
+      #         exit 1
+      #     fi
 
-          git fetch "${UPSTREAM_BRANCH_NAME%%/*}"
+      #     git fetch "${UPSTREAM_BRANCH_NAME%%/*}"
 
-          if ! UPSTREAM_SHA="$(git rev-parse "$UPSTREAM_BRANCH_NAME")"; then
-              printf >&2 '%s\n' "::error::Unable to determine upstream branch sha!"
-              exit 1
-          fi
+      #     if ! UPSTREAM_SHA="$(git rev-parse "$UPSTREAM_BRANCH_NAME")"; then
+      #         printf >&2 '%s\n' "::error::Unable to determine upstream branch sha!"
+      #         exit 1
+      #     fi
 
-          HEAD_SHA="$(git rev-parse HEAD)"
+      #     HEAD_SHA="$(git rev-parse HEAD)"
 
-          if [ "$HEAD_SHA" != "$UPSTREAM_SHA" ]; then
-              printf >&2 '%s\n' "[HEAD SHA] $HEAD_SHA != $UPSTREAM_SHA [UPSTREAM SHA]"
-              printf >&2 '%s\n' "::error::Upstream has changed, aborting release..."
-              exit 1
-          fi
+      #     if [ "$HEAD_SHA" != "$UPSTREAM_SHA" ]; then
+      #         printf >&2 '%s\n' "[HEAD SHA] $HEAD_SHA != $UPSTREAM_SHA [UPSTREAM SHA]"
+      #         printf >&2 '%s\n' "::error::Upstream has changed, aborting release..."
+      #         exit 1
+      #     fi
 
-          printf '%s\n' "Verified upstream branch has not changed, continuing with release..."
+      #     printf '%s\n' "Verified upstream branch has not changed, continuing with release..."
 
       - name: Set up Node.js
         uses: actions/setup-node@v6
